-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgRn77GRRujM7o+osn
k4pARHAWQFL9djUmYmgIVUQbk4egCgYIKoZIzj0DAQehRANCAARFskb7THAy3rYf
x4u00MxT8ZyVeyasyyeyCBqM9n+iQS2sg5bnn3e9cNdIAvxOFBrssDuAecqpNpfT
4tMnEWKi
-----END PRIVATE KEY-----